// Flutter single-file demo app: Free/Cheap Books + Firebase Auth
// Save as lib/main.dart
// You must generate firebase_options.dart using the FlutterFire CLI (flutterfire configure)

/*
pubspec.yaml (add these deps):

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.6.0
  flutter_hooks: ^0.18.6 # optional

Run:
  flutter pub get
  flutterfire configure -> generates firebase_options.dart
  flutter run
*/

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const BooksApp());
}

class BooksApp extends StatelessWidget {
  const BooksApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Free Books',
      theme: ThemeData(primarySwatch: Colors.indigo),
      home: const RootPage(),
    );
  }
}

class RootPage extends StatelessWidget {
  const RootPage({super.key});

  @override
  Widget build(BuildContext context) {
    // StreamBuilder listens to auth state; user remains signed in between app restarts
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        final user = snapshot.data;
        if (user == null) return const AuthPage();
        return HomePage(user: user);
      },
    );
  }
}

// ------------------ Auth UI ------------------
class AuthPage extends StatefulWidget {
  const AuthPage({super.key});

  @override
  State<AuthPage> createState() => _AuthPageState();
}

class _AuthPageState extends State<AuthPage> {
  final _emailCtrl = TextEditingController();
  final _pwCtrl = TextEditingController();
  bool _isRegister = false;
  String? _error;
  bool _loading = false;

  Future<void> _submit() async {
    final email = _emailCtrl.text.trim();
    final password = _pwCtrl.text;

    // Validation
    if (email.isEmpty || password.isEmpty) {
      setState(() => _error = 'Please enter email and password');
      return;
    }

    if (password.length < 6) {
      setState(() => _error = 'Password must be at least 6 characters');
      return;
    }

    setState(() {
      _error = null;
      _loading = true;
    });

    try {
      if (_isRegister) {
        // Register new user (password stored securely by Firebase Auth)
        final cred = await FirebaseAuth.instance.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );
        // Create a basic user document in Firestore
        await FirebaseFirestore.instance
            .collection('users')
            .doc(cred.user!.uid)
            .set({
              'email': cred.user!.email,
              'createdAt': FieldValue.serverTimestamp(),
            });
      } else {
        // Sign in existing user
        await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: email,
          password: password,
        );
      }
    } on FirebaseAuthException catch (e) {
      String errorMsg = 'Authentication error';
      if (e.code == 'email-already-in-use') {
        errorMsg = 'Email already in use';
      } else if (e.code == 'invalid-email') {
        errorMsg = 'Invalid email format';
      } else if (e.code == 'weak-password') {
        errorMsg = 'Password is too weak';
      } else if (e.code == 'user-not-found') {
        errorMsg = 'User not found';
      } else if (e.code == 'wrong-password') {
        errorMsg = 'Wrong password';
      } else if (e.code == 'operation-not-allowed') {
        errorMsg = 'Operation not allowed';
      } else {
        errorMsg = e.message ?? 'Unknown error';
      }
      setState(() => _error = errorMsg);
    } catch (e) {
      setState(() => _error = 'Error: ${e.toString()}');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Welcome')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              controller: _emailCtrl,
              keyboardType: TextInputType.emailAddress,
              decoration: const InputDecoration(labelText: 'Email'),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _pwCtrl,
              obscureText: true,
              decoration: const InputDecoration(labelText: 'Password'),
            ),
            const SizedBox(height: 20),
            if (_error != null)
              Text(_error!, style: const TextStyle(color: Colors.red)),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: _loading ? null : _submit,
              child: _loading
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : Text(_isRegister ? 'Register' : 'Login'),
            ),
            TextButton(
              onPressed: () => setState(() => _isRegister = !_isRegister),
              child: Text(
                _isRegister ? 'Have an account? Login' : 'No account? Register',
              ),
            ),
            const SizedBox(height: 12),
            TextButton(
              onPressed: () async {
                // Simple password reset flow
                final email = _emailCtrl.text.trim();
                if (email.isEmpty) return;
                await FirebaseAuth.instance.sendPasswordResetEmail(
                  email: email,
                );
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('Password reset sent (if account exists).'),
                    ),
                  );
                }
              },
              child: const Text('Forgot password?'),
            ),
          ],
        ),
      ),
    );
  }
}

// ------------------ Home ------------------
class HomePage extends StatelessWidget {
  final User user;
  const HomePage({super.key, required this.user});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Free & Cheap Books'),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () async => await FirebaseAuth.instance.signOut(),
            tooltip: 'Logout',
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(12.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Signed in as ${user.email ?? 'Anonymous'}'),
                ElevatedButton(
                  onPressed: () async {
                    // Add a demo book to Firestore (for testing/demo purposes)
                    await FirebaseFirestore.instance.collection('books').add({
                      'title': 'Sample Book',
                      'author': 'Author',
                      'price': 0,
                      'createdAt': FieldValue.serverTimestamp(),
                      'uploader': user.uid,
                    });
                  },
                  child: const Text('Add Sample Book'),
                ),
              ],
            ),
          ),
          const Expanded(child: BooksList()),
        ],
      ),
    );
  }
}

class BooksList extends StatelessWidget {
  const BooksList({super.key});

  @override
  Widget build(BuildContext context) {
    final booksCol = FirebaseFirestore.instance
        .collection('books')
        .orderBy('createdAt', descending: true);
    return StreamBuilder<QuerySnapshot>(
      stream: booksCol.snapshots(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        final docs = snapshot.data?.docs ?? [];
        if (docs.isEmpty) {
          return const Center(child: Text('No books yet'));
        }
        return ListView.builder(
          itemCount: docs.length,
          itemBuilder: (context, i) {
            final d = docs[i];
            final data = d.data() as Map<String, dynamic>;
            final price = data['price'] ?? 0;
            return ListTile(
              title: Text('${data['title'] ?? 'Untitled'}'),
              subtitle: Text(
                '${data['author'] ?? 'Unknown'} • ${price == 0 ? 'Free' : 'R\$ $price'}',
              ),
              trailing: IconButton(
                icon: const Icon(Icons.info_outline),
                onPressed: () => showDialog(
                  context: context,
                  builder: (_) => AlertDialog(
                    title: Text(data['title'] ?? 'Details'),
                    content: Column(
                      mainAxisSize: MainAxisSize.min,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Author: ${data['author'] ?? 'Unknown'}'),
                        const SizedBox(height: 8),
                        Text('Price: ${price == 0 ? 'Free' : 'R\$ $price'}'),
                        const SizedBox(height: 8),
                        Text('Uploaded by: ${data['uploader'] ?? 'n/a'}'),
                      ],
                    ),
                    actions: [
                      TextButton(
                        onPressed: () => Navigator.pop(context),
                        child: const Text('Close'),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        );
      },
    );
  }
}

/*
Security notes & next steps:
- This demo uses Firebase Authentication for handling passwords. DO NOT store plaintext passwords in Firestore.
- Firebase stores passwords securely (hashed) and manages authentication safely.
- To allow users to upload books (PDFs) add firebase_storage and secure rules in Firebase Console.
- Set Firestore security rules so users can only write appropriate data.
- Consider adding roles (uploader/admin) in user documents to manage content moderation.
- For production, enable email verification, rate limits, and monitoring for abuse.
*/
